language: python
python:
  - "3.6"
  - "3.7" 
  - "3.8"
install: 
  #NOTE: For conda in the future
  # - "pip install pytest" #instalamos pytest
  # - "pip install -r requirements.txt" #instalamos todas las bibliotecas
  # - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
  #     wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  #   else
  #     wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  #   fi
  # - bash miniconda.sh -b -p $HOME/miniconda
  # - source "$HOME/miniconda/etc/profile.d/conda.sh"
  # - hash -r
  # - conda config --set always_yes yes --set changeps1 no
  # - conda update -q conda
  # # Useful for debugging any issues with conda
  # - conda info -a
  # - conda config --add channels conda-forge
  # - conda config --add channels anaconda
  # - conda config --add channels menpo
  # - conda config --add channels bioconda
  - pip3 install virtualenv
  - python3 -m venv "/home/travis/build/arubiales/scikit-route/scikit-route-venv"
  - source activate scikit-route-venv/
  - pip install --upgrade pip
  - pip install Cython
  - pwd
  - ls -lisa
  - python setup.py sdist bdist_wheel
  - pip install dist/skroute*.whl

script:
  - cd ..
  - python -m pytest --cov -v scikit-route/skroute/_utils/tests
  - python -m pytest --cov -v scikit-route/skroute/_validators/tests
  - python -m pytest --cov -v scikit-route/skroute/heuristics/brute/tests
  - python -m pytest --cov -v scikit-route/skroute/heuristics/NRBS/tests
  - python -m pytest --cov -v scikit-route/skroute/metaheuristics/genetics/tests
  - python -m pytest --cov -v scikit-route/skroute/metaheuristics/simulated_annealing/tests
  - python -m pytest --cov -v scikit-route/skroute/metaheuristics/som/tests
  - python -m pytest --cov -v scikit-route/skroute/metaheuristics/tabu_search/tests
  - bash <(curl -s https://codecov.io/bash) #Para el coverage del código
