site_name: Scikit Route
nav: 
  - Home: index.md
  - Installation instructions: Installation.md
  - Tutorial: Tutorial.md
  - Datasets: Datasets.md
  - Preprocessing: Preprocessing.md
  - Clustering: Clustering.md
  - Genetics: Genetics.md
  - Simmulated Annealing: Simmulated_Annealing.md
  - Tabu Search: TabuSearch.md
  - SOM: SOM.md
  - BruteForce: BruteForce.md
  - Node Ranking Based on Stats (NRBS): NRBS.md 
  - Utilities: Utilities.md
  - About: about.md

markdown_extensions:
  - pymdownx.arithmatex
  - admonition
  - mdx_math

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

theme: readthedocs

